### PR TITLE
Add OpenDKIM Domain Key handling

### LINKED ISSUE #335: Feature Request: DKIM
Hello,

attached patch for postfixadmin-3.2 adding opendkim support. I used version
1.0 several years on several servers. It was partially independent on
postfixadmin (only authentication for mysql and global-admin used). Now I added
support for domain admins and pagination. This version is fresh.

new files:
public/dkim.php
public/css/dkim.css

changed file:
templates/menu.tpl

I am not programmer, so source code is....maybe inspiration or base for true 
programmer. But it works for me.

#in mysql pfa database

CREATE TABLE `dkim_key` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
   `name` varchar(255) NOT NULL,
   `selector` varchar(255) NOT NULL,
   `private_key` text NOT NULL,
   PRIMARY KEY (`id`) );

CREATE TABLE `dkim_signing_table` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `sender` varchar(255) NOT NULL,
  `key_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `key_id` (`key_id`),
  CONSTRAINT `dkim_signing_table_ibfk_1` FOREIGN KEY (`key_id`) REFERENCES `dkim_key` (`id`) );

GRANT SELECT ON `dbname`.`dkim_key` TO 'opendkim'@'localhost' identified by 'password';
GRANT SELECT ON `dbname`.`dkim_signing_table` TO 'opendkim'@'localhost'

#in opendkim.conf
KeyTable     dsn:mysql://opendkim:password@localhost/dbname/table=dkim_key?keycol=id?datacol=name,selector,private_key
SigningTable dsn:mysql://opendkim:password@localhost/dbname/table=dkim_signing_table?keycol=sender?datacol=key_id

[postfixadmin-3.2-dkim.txt](https://github.com/postfixadmin/postfixadmin/files/4262689/postfixadmin-3.2-dkim.txt)

### PR DESCRIPTION
**Pull request by Freddo3000**
This pull request adds support for OpenDKIM's [SQL Backend](https://github.com/trusteddomainproject/OpenDKIM/blob/master/opendkim/README.SQL) for KeyTable and SigningTable, allowing domain admins to add domain keys for their domains. There can be multiple domain keys for each domain, and the signing table allows admins to assign certain keys to domains and/or mailboxes.

Images
---

image
dkim-add-domain-key
image
dkim-add-sign-table-entry

Notes
---

* This has not been tested with PostgreSQL, as I don't have experience working with it
* This is also my first venture into PHP, though I tried to follow in the tracks of other components.
* I'd like to have the two tables on a single page, but couldn't find any easy way to do it. 
* I'd also like to add the domain key description to the domain key option when creating sign table entries, though same issue as above.
* I haven't done deep testing with OpenDKIM beyond that it reads from the database, as I don't have a full postfix/dovecot/etc setup on hand.

References
---

* http://www.opendkim.org/opendkim.8.html
* http://www.opendkim.org/opendkim.conf.5.html
* https://github.com/trusteddomainproject/OpenDKIM/blob/master/opendkim/README.SQL
* http://www.opendkim.org/opendkim-genkey.8.html

---

Resolves #335

### CODE REVIEW

**Review by DavidGoodwin — APPROVED** [review]
Looks good!

**Comment by termonoid** [comment]
Is it possible to automatically generate keypair using opendkim-genkey?
Also, IMO, would be nice to show only public key as DNS record, to just copy-paste it

**Comment by Freddo3000** [comment]
> Is it possible to automatically generate keypair using opendkim-genkey? Also, IMO, would be nice to show only public key as DNS record, to just copy-paste it

Probably possible, though I don't have the time to add it in this PR.

**Comment by DavidGoodwin** [comment]
> Is it possible to automatically generate keypair using opendkim-genkey? Also, IMO, would be nice to show only public key as DNS record, to just copy-paste it

Yes, I've been thinking the same :) 

I've only not merged it because I've not had time to try using it ....

**Comment by DavidGoodwin** [comment]
Code works on PostgreSQL now - the original SQL in upgrade.php didn't work with PostgreSQL (it didn't like backticks, it didn't like an index being created in the table spec) - so I just copied it into it's own _pgsql type function.

**Comment by Freddo3000** [comment]
> I did two follow-up fixes:
> 
>     * [6a53b1a](https://github.com/postfixadmin/postfixadmin/commit/6a53b1ab882446dda7111d63664afb06f4adf9af): Drop duplicate db_delete() call from DkimHandler and DkimsigningHandler. The hardcoded name is the same as $this->db_table, which effectively means running the same query twice. One of them is enough.
> 
>     * [a8b4e3f](https://github.com/postfixadmin/postfixadmin/commit/a8b4e3f4358425ef06b08397637b31ac25e00be5): Update translations with DKIM texts so that DKIM support also works in other languages (done with `language-update.sh --patch`)
> 
> 
> I also have a question: Would it be ok for you to rename the `txtlarge` field type to `txta` (short for "textarea")? That would have the small advantage to keep the type "column" in init_struct() limited to 4 chars, instead of widening it just for one field type.

I see no problem with that

**Comment by cboltz** [comment]
`txtlarge` -> `txta` rename done.

**Comment by ETE-Design** [comment]
> > Is it possible to automatically generate keypair using opendkim-genkey? Also, IMO, would be nice to show only public key as DNS record, to just copy-paste it
> 
> Yes, I've been thinking the same :)
> 
> I've only not merged it because I've not had time to try using it ....

@DavidGoodwin This would be a great feature to add :-)

**Pull request merged**
