### PR TITLE
Make quota levels configurable

### PR DESCRIPTION
**Pull request by csware**
Allow users to change the thresholds for quota levels.

### CODE REVIEW

**Comment by DavidGoodwin** [comment]
If you could add something into your code so the two new config variables ( quota_level_high_pct and quota_level_med_pct ) have default values matching what they were ( 55 and 90 ) that would be great. 

(I suspect many people will have customised their config file, and may not pick up new entries if/when they upgrade).

**Comment by DavidGoodwin** [comment]
(Thanks for taking the time to contribute!)

**Comment by csware** [comment]
I thought config.inc.php is the default value.

**Comment by DavidGoodwin** [comment]
> I thought config.inc.php is the default value as people should use a local version.

Yes it is .... or should be. But some people only have a config.inc.php, and do not change that file when upgrading.

**Comment by csware** [comment]
Please give a hint where and how to do.

**Comment by DavidGoodwin** [comment]
Nevermind; the code isn't really setup to support that. Pretend I didn't ask ;-)

**Pull request merged**
