### PR TITLE
Update install.sh

### PR DESCRIPTION
**Pull request by muhammadali175302**
Updated Not Installing Error ..

### CODE REVIEW

**Comment by DavidGoodwin** [comment]
Thanks for taking time to contribute.

What's wrong with having --no-dev ?

**Comment by muhammadali175302** [comment]
it cannot be installed using google colab ..

**Comment by DavidGoodwin** [comment]
What's Google Colab? Googling implies it's just something for python?

(It would have helped me if you'd been a bit more descriptive in your PR ... "Updated Not Installing Error..." doesn't mean much to me. It does explain why these changes should be made).

**Comment by muhammadali175302** [comment]
sorry ....

**Pull request closed without merging**
