### PR TITLE
Added support for mkpasswd encryption method

### PR DESCRIPTION
**Pull request by Sopsy**
This makes it possible to use postfixadmin with eg. SHA-512 and with a rounds -setting on a server without Dovecot installed.

Useful when installed on a different server than where Dovecot resides, eg. a webhost.

FYI: mkpasswd is installed on debian/ubuntu with the package "whois":

New config keys:
$CONF['mkpasswd'] = "/usr/bin/mkpasswd";
$CONF['mkpasswd_rounds'] = 30000; // Only supported by sha-xxx

New values for encrypt:
$CONF['encrypt'] = 'mkpasswd:des'; // Might not be supported by dovecot/postfix at all
$CONF['encrypt'] = 'mkpasswd:md5';
$CONF['encrypt'] = 'mkpasswd:sha-256';
$CONF['encrypt'] = 'mkpasswd:sha-512';

### CODE REVIEW

**Comment by cboltz** [comment]
It seems [crypt()](http://php.net/crypt) also supports these hashing methods and specifying the number of rounds. Would that be an alternative?
(I'd prefer it because it doesn't rely on an external program.)

Note: The 'system' hashing type uses crypt(), but it doesn't allow to specify the hashing method yet. Adding support for that (as "system:sha-256:30000") would be nice ;-)
Actually there's already a patch that promises to do something like that - https://sourceforge.net/p/postfixadmin/patches/121/ (untested).

**Comment by Sopsys** [comment]
I'll check if I can rewrite the code to use crypt() instead of mkpasswd. That just seemed to be the easy way out. I'll return to this later.

Thanks for the idea!

**Comment by cboltz** [comment]
You might want to look at #32 ;-)  I only had a quick look at it, but it probably does what you want.

**Comment by DavidGoodwin** [comment]
Closing - I think this is handled in the code in #32 and there's no benefit to this patch being merged (aside from making the hashing options yet more complex)

**Pull request closed without merging**
