### PR TITLE
reuse $incpath variable instead of dirname

### PR DESCRIPTION
**Pull request by vakartel**

### CODE REVIEW

**Comment by DavidGoodwin** [comment]
Are there circumstances where $incpath would be correct, and dirname(__FILE__) wouldn't be?

**Comment by vakartel** [comment]
just to not run filesystem-aware function dirname() second time because we have its result in $incpath variable

**Comment by DavidGoodwin** [comment]
Oh right. I'm not sure that works in this instance - the code looks like : 

image


$incpath is defined outside of the function 'postfixadmin_autoload' - so wouldn't be visible inside it by default (you'd need to 'global' it).

I think the code also uses a $incpath somewhere else (in public/users?) so I'm not sure doing this is a good idea.

**Comment by vakartel** [comment]
> $incpath is defined outside of the function 'postfixadmin_autoload' - so wouldn't be visible inside it

exactly

**Pull request closed without merging**
